### ISSUE TITLE
Addon labels

### ISSUE THREAD

**Issue by DadamaldaDad** [blueprint-site/blueprint-site.github.io#64]
Adding labels to some addons could be useful, because modrinth categories are too generic. Not all addons have to have labels, the most important ones could be "can't be installed alongside create" or just "fork" (eg. Create fabric sodium fix) and "not family friendly" (eg. Create: Estr*gen)
Of course there can be more added overtime. If this would be too hard to manage and keep up to date, I'm sorry for having too many ideas, no pressure.
I'm imagining each label being an icon with a description when hovered, but the UI design can change.

**Comment by TheReal-Flo** [comment]
We should probably look into this

**Comment by JavaBoii** [comment]
Acknowledged. Updating the Issue for devs:

**Current State (Is):**
- Labels for addons are currently too generic due to the limitations of Modrinth categories. 
- Not all addons clearly convey their compatibility issues or content warnings.

**Desired State (Should):**
- Implement specific labels for the most important addons to better guide users. Key labels to include:
   - **"Cannot be installed alongside CREATE"** for compatibility issues.
   - **"Fork"** for derivatives like "Create fabric sodium fix".
   - **"Not family friendly"** for content warnings, such as in "Create: Estr*gen".

**Suggested Features:**
- [ ] **Icon-Based Labels:** Each label should be represented by an icon, with a tooltip description on hover to provide clarity without cluttering the interface.
- [ ] **Adaptive UI Design:** Start with icon tooltips but remain open to UI adjustments based on user feedback and practicality.

**Additional Notes:**
- The possibility of adding more labels over time as needed.
- Concerns about the difficulty of managing and keeping the labels up to date are noted; the implementation plan should consider ease of maintenance.

**Conclusion:**
This enhancement aims to improve user navigation and information accessibility on the site without overwhelming the maintenance team. Suggestions for gradual implementation are welcome.

**Comment by yehorscode** [comment]
I have an idea for more tags like:
- has ponder menu

**Comment by DadamaldaDad** [comment]
Would be awesome if you let the community help with keeping labels up to date.
I have some coding skills, but I'm bad at understanding other people's code, so if saved in a text or json file, I have used ~40 Create addons and can help with adding labels.
The ponder menu idea is really good, I just didn't want to include examples requiring much maintenance.

**Comment by yehorscode** [comment]
> Would be awesome if you let the community help with keeping labels up to date.
> I have some coding skills, but I'm bad at understanding other people's code, so if saved in a text or json file, I have used ~40 Create addons and can help with adding labels.
> The ponder menu idea is really good, I just didn't want to include examples requiring much maintenance.

Nice idea! I think i'll make a python app for adding labels
